//export const FETCH_TREATMENTS = "FETCH_TREATMENTS"
//export const SET_TREATMENTS = "SET_TREATMENTS"
//export const ADD_TREATMENT = "ADD_TREATMENT"

// export const ADD_APPOINTMENT = "ADD_APPOINTMENT"


// export const UPDATE_APPOINTMENT_LOCATION = "UPDATE_APPOINTMENT_LOCATION"
// export const ADD_APPOINTMENT_LOCATION = 'ADD_APPOINTMENT_LOCATION'
// export const APPOINTMENT_TIME = 'APPOINTMENT_TIME'
// export const APPOINTMENT_PAYMENT = 'APPOINTMENT_PAYMENT'